schemaVersion = 1
commandMode = "COMMAND_CUSTOM"
command = "delhome"

[[children]]
child = "name"
type = "argument"
argumentType = "minecraft:word"

[children.suggestionProvider]
suggestionMode = "DATABASE_STARTS_WITH"
suggestion = "$executor_name().home.suggestions"

[[children.actions]]
command = "commandaliases database match $executor_name().home.suggestions.{{name}}"
commandType = "SERVER"
messageIfUnsuccessful = "$executor_name() [{{name}}] home does not exist!"
requireSuccess = true

[[children.actions]]
command = "commandaliases database delete $executor_name().home.suggestions.{{name}}"
commandType = "SERVER"
requireSuccess = true

[[children.actions]]
command = "commandaliases database delete $executor_name().home.{{name}}.command"
commandType = "SERVER"
messageIfSuccessful = "$executor_name() [{{name}}] home has been deleted!"

[[actions]]
command = "delhome main"
commandType = "CLIENT"
