commandMode = "COMMAND_CUSTOM"

[customCommand]
parent = "tpa"

[[customCommand.children]]
child = "player"
type = "argument"
argumentType = "minecraft:player"

[[customCommand.children.actions]]
command = "commandaliases compute equals {{player}} $executor_name()"
commandType = "SERVER"
successfulMessage = "You can not request to teleport to yourself!"

[[customCommand.children.actions.unsuccessfulActions]]
command = "commandaliases database contains {{player}}.tpa.last_player"
commandType = "SERVER"
requireSuccess = true
successfulMessage = "{{name}} has a pending request! Please wait..."

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database put {{player}}.tpa.last_player $executor_name()"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = 'tellraw {{player}} "$executor_name() has requested to teleport to you. Type /tpaccept to accept this request. This request will expire in 60 seconds."'
commandType = "SERVER"
requireSuccess = true
successfulMessage = "You have requested to teleport to {{player}}."

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
sleep = "60000"

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
id = "{{player}}.tpa.event.$executor_name()"
command = "commandaliases database contains {{player}}.tpa.last_player"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database delete {{player}}.tpa.last_player"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = 'tellraw {{player}} "The request has expired."'
commandType = "SERVER"
successfulMessage = "The request to {{player}} has expired."
