commandMode = "COMMAND_CUSTOM"

[customCommand]
parent = "tpahere"

[[customCommand.children]]
child = "player"
type = "argument"
argumentType = "minecraft:player"

[[customCommand.children.actions]]
command = "commandaliases compute equals {{player}} $executor_name()"
commandType = "SERVER"
successfulMessage = "You can not request to teleport to yourself!"

[[customCommand.children.actions.unsuccessfulActions]]
command = "commandaliases database contains {{player}}.tpahere.last_player"
commandType = "SERVER"
requireSuccess = true
successfulMessage = "{{name}} has a pending request! Please wait..."

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database put {{player}}.tpahere.last_player $executor_name()"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database put {{player}}.tpahere.dimension $get_dimension($executor_name())"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database put {{player}}.tpahere.x $get_block_pos_x($executor_name())"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database put {{player}}.tpahere.y $get_block_pos_y($executor_name())"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database put {{player}}.tpahere.z $get_block_pos_z($executor_name())"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database put {{player}}.tpahere.yaw $get_yaw($executor_name())"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database put {{player}}.tpahere.pitch $get_pitch($executor_name())"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = 'tellraw {{player}} "$executor_name() has requested you to teleport to them. Type /tpaccept to accept this request. This request will expire in 60 seconds."'
commandType = "SERVER"
requireSuccess = true
successfulMessage = "You have requested to teleport to {{player}}."

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
sleep = "60000"

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
id = "{{player}}.tpahere.event.$executor_name()"
command = "commandaliases database contains {{player}}.tpahere.last_player"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database delete {{player}}.tpahere.last_player"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database delete {{player}}.tpahere.dimension"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database delete {{player}}.tpahere.x"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database delete {{player}}.tpahere.y"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database delete {{player}}.tpahere.z"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database delete {{player}}.tpahere.yaw"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = "commandaliases database delete {{player}}.tpahere.pitch"
commandType = "SERVER"
requireSuccess = true

[[customCommand.children.actions.unsuccessfulActions.unsuccessfulActions]]
command = 'tellraw {{player}} "The request has expired."'
commandType = "SERVER"
successfulMessage = "The request to {{player}} has expired."
